import Foundation

enum WritingPromptService {
    /// One prompt per day of the year, cycled. Every language table must stay the
    /// same length and order so a given date shows the same prompt everywhere.
    static let prompts: [AppLanguage: [String]] = [
        .en: [
            "What made you smile today?",
            "Describe a moment you felt grateful for.",
            "What's something new you learned recently?",
            "Write about a person who made your day better.",
            "What would you tell your future self?",
            "Describe the weather and how it made you feel.",
            "What's a small victory you had today?",
            "Write about something you're looking forward to.",
            "What's on your mind right now?",
            "Describe your favorite moment of the day.",
            "What challenge did you face today?",
            "Write about a place you'd like to visit.",
            "What made today different from yesterday?",
            "Describe something beautiful you noticed.",
            "What's a habit you'd like to build?",
            "Write about someone you miss.",
            "What was the best thing you ate today?",
            "Describe how you're feeling in three words.",
            "What's a book, movie, or song on your mind?",
            "Write about a goal you're working toward.",
            "What would make tomorrow great?",
            "Describe a conversation that stuck with you.",
            "What's something you're proud of?",
            "Write about your morning routine today.",
            "What's a kind thing someone did for you?",
            "Describe the sounds around you right now.",
            "What lesson did today teach you?",
            "Write about something that made you laugh.",
            "What are you thankful for this week?",
            "If today were a color, what would it be and why?",
        ],
        .zhHans: [
            "今天什么事让你微笑了？",
            "描述一个让你感到感激的时刻。",
            "你最近学到了什么新东西？",
            "写写一个让你今天变得更好的人。",
            "你想对未来的自己说什么？",
            "描述一下今天的天气和它带给你的感受。",
            "今天你取得了什么小胜利？",
            "写写你期待的事情。",
            "你现在在想什么？",
            "描述今天你最喜欢的时刻。",
            "你今天面对了什么挑战？",
            "写写一个你想去的地方。",
            "今天和昨天有什么不同？",
            "描述你注意到的美好事物。",
            "你想养成什么习惯？",
            "写写一个你想念的人。",
            "今天你吃过最好吃的是什么？",
            "用三个词描述你现在的感受。",
            "你脑海中有什么书、电影或歌曲？",
            "写写你正在努力实现的目标。",
            "什么能让明天变得很棒？",
            "描述一次让你印象深刻的对话。",
            "你为什么感到自豪？",
            "写写你今天早上的日常。",
            "有人为你做过什么善意的事？",
            "描述你现在周围的声音。",
            "今天教会了你什么？",
            "写写让你笑的事情。",
            "这周你感激什么？",
            "如果今天是一种颜色，会是什么？为什么？",
        ],
        .zhHant: [
            "今天有什麼事讓你笑了？",
            "描述一個讓你心懷感謝的時刻。",
            "你最近學到了什麼新東西？",
            "寫寫一個讓你今天更美好的人。",
            "你想對未來的自己說什麼？",
            "描述今天的天氣，和它帶給你的感受。",
            "今天你贏得了什麼小小的勝利？",
            "寫寫你正在期待的事。",
            "你現在心裡在想什麼？",
            "描述今天你最喜歡的那一刻。",
            "你今天遇到了什麼挑戰？",
            "寫寫一個你想去的地方。",
            "今天和昨天有什麼不一樣？",
            "描述你注意到的美好事物。",
            "你想養成什麼習慣？",
            "寫寫一個你想念的人。",
            "今天你吃到最好吃的是什麼？",
            "用三個詞描述你現在的感受。",
            "你腦海裡有哪本書、哪部電影或哪首歌？",
            "寫寫你正在努力的目標。",
            "什麼能讓明天變得很棒？",
            "描述一場讓你記到現在的對話。",
            "有什麼事讓你覺得驕傲？",
            "寫寫你今天早上的日常。",
            "有人為你做過什麼溫暖的事？",
            "描述你現在周圍的聲音。",
            "今天教會了你什麼？",
            "寫寫讓你笑出來的事。",
            "這一週你想感謝什麼？",
            "如果今天是一個顏色，會是什麼？為什麼？",
        ],
        .ja: [
            "今日、笑顔になったのはどんなとき？",
            "ありがたいと思えた瞬間を書いてみましょう。",
            "最近知った新しいことは？",
            "今日をよくしてくれた人について書いてみましょう。",
            "未来の自分に伝えたいことは？",
            "今日の天気と、そのときの気持ちを書いてみましょう。",
            "今日の小さな勝利は？",
            "楽しみにしていることを書いてみましょう。",
            "いま頭に浮かんでいることは？",
            "今日いちばん好きだった時間を書いてみましょう。",
            "今日ぶつかった壁は？",
            "行ってみたい場所について書いてみましょう。",
            "昨日と違ったのはどんなところ？",
            "きれいだなと思ったものを書いてみましょう。",
            "身につけたい習慣は？",
            "会いたい人について書いてみましょう。",
            "今日いちばんおいしかったものは？",
            "いまの気持ちを三つの言葉で。",
            "気になっている本・映画・音楽は？",
            "いま向かっている目標について書いてみましょう。",
            "明日をいい日にするものは何だろう？",
            "心に残った会話を書いてみましょう。",
            "自分をほめたいことは？",
            "今日の朝の過ごし方を書いてみましょう。",
            "誰かにしてもらったやさしいことは？",
            "いま聞こえてくる音を書いてみましょう。",
            "今日、学べたことは？",
            "笑ってしまったことを書いてみましょう。",
            "今週ありがたかったことは？",
            "今日を色にたとえるなら？それはなぜ？",
        ],
        .ko: [
            "오늘 웃게 만든 일은 무엇이었나요?",
            "고맙다고 느낀 순간을 적어 보세요.",
            "요즘 새로 알게 된 것이 있나요?",
            "오늘을 더 좋게 만들어 준 사람에 대해 적어 보세요.",
            "미래의 나에게 무슨 말을 해 주고 싶나요?",
            "오늘 날씨와 그때의 기분을 적어 보세요.",
            "오늘 이룬 작은 승리는 무엇인가요?",
            "기다려지는 일에 대해 적어 보세요.",
            "지금 무슨 생각을 하고 있나요?",
            "오늘 가장 좋았던 순간을 적어 보세요.",
            "오늘 마주한 어려움은 무엇이었나요?",
            "가 보고 싶은 곳에 대해 적어 보세요.",
            "오늘은 어제와 무엇이 달랐나요?",
            "예쁘다고 느낀 것을 적어 보세요.",
            "만들고 싶은 습관이 있나요?",
            "보고 싶은 사람에 대해 적어 보세요.",
            "오늘 가장 맛있게 먹은 건 무엇인가요?",
            "지금 기분을 세 단어로 적어 보세요.",
            "요즘 마음에 남은 책, 영화, 노래가 있나요?",
            "향해 가고 있는 목표에 대해 적어 보세요.",
            "내일을 좋은 날로 만들어 줄 건 무엇일까요?",
            "오래 남은 대화를 적어 보세요.",
            "스스로 대견한 일이 있나요?",
            "오늘 아침을 어떻게 보냈는지 적어 보세요.",
            "누군가 베풀어 준 다정한 일이 있나요?",
            "지금 주변에서 들리는 소리를 적어 보세요.",
            "오늘은 무엇을 배웠나요?",
            "웃음이 났던 일을 적어 보세요.",
            "이번 주에 감사한 일은 무엇인가요?",
            "오늘을 색으로 표현하면? 그 이유는요?",
        ],
        .es: [
            "¿Qué te hizo sonreír hoy?",
            "Describe un momento por el que te sentiste agradecido.",
            "¿Qué has aprendido últimamente?",
            "Escribe sobre alguien que te mejoró el día.",
            "¿Qué le dirías a tu yo del futuro?",
            "Describe el tiempo de hoy y cómo te hizo sentir.",
            "¿Cuál fue tu pequeña victoria de hoy?",
            "Escribe sobre algo que estés esperando con ganas.",
            "¿Qué tienes en la cabeza ahora mismo?",
            "Describe tu momento favorito del día.",
            "¿A qué te enfrentaste hoy?",
            "Escribe sobre un lugar al que te gustaría ir.",
            "¿En qué fue hoy distinto de ayer?",
            "Describe algo bonito en lo que te fijaste.",
            "¿Qué hábito te gustaría construir?",
            "Escribe sobre alguien a quien echas de menos.",
            "¿Qué es lo mejor que comiste hoy?",
            "Describe cómo te sientes en tres palabras.",
            "¿Qué libro, película o canción te ronda?",
            "Escribe sobre una meta en la que estás trabajando.",
            "¿Qué haría que mañana fuera un buen día?",
            "Describe una conversación que se te quedó grabada.",
            "¿De qué te sientes orgulloso?",
            "Escribe sobre cómo empezó tu mañana de hoy.",
            "¿Qué gesto amable tuvo alguien contigo?",
            "Describe los sonidos que te rodean ahora.",
            "¿Qué te ha enseñado el día de hoy?",
            "Escribe sobre algo que te hizo reír.",
            "¿Por qué estás agradecido esta semana?",
            "Si hoy fuera un color, ¿cuál sería y por qué?",
        ],
    ]

    static func promptForDate(_ date: Date) -> String {
        let table = AppLanguage.current.pick(prompts)
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: date) ?? 1
        return table[(dayOfYear - 1) % table.count]
    }
}
